export { default as BackButton } from './BackButton/index.vue'
export { default as NextPageButton } from './NextPageButton/index.vue'
export { default as ThemeSwitcher } from './ThemeSwitcher/index.vue'
export { default as LanguageSwitcher } from './LanguageSwitcher/index.vue'
export { default as Header } from './Header/index.vue'
export { default as Footer } from './Footer/index.vue'
